import { createEffect } from '../gameSchema/current/defaults';
import { HAKI_TYPES, NPC_STAT_IDS, NPC_STATUSES, PLAYER_STAT_IDS, type Effect, type GameRegistries } from '../gameSchema/current/contract';
import { IdSelect, NumberInput } from './EditorPrimitives';

export const EFFECT_TYPES: Effect['type'][] = [
  'setFlag','clearFlag','addItem','removeItem','addTrait','removeTrait','modifyStat','modifyHealth','acquireShip','modifyShipHealth','addCargoItem','removeCargoItem','resolveShipReplacement','modifyBerries','loseShip',
  'moveToLocation','setBirthLocation','setNpcStatus','setNpcPassenger','setLeadership','modifyNpcRelationship','modifyNpcStat','scheduleEvent','queueImmediateEvent','setCareerPhase','setRace',
  'setOriginSea','setAffiliation','setFamilyStructure','setSocialClass','endCareer','consumeDevilFruit','increaseDevilFruitAwakening','awakenHaki','raiseConquerorHakiTo','setNpcDevilFruit','increaseNpcDevilFruitAwakening','raiseNpcHakiTo',
  'setCareerAffiliation','modifyReputation','setBounty','modifyBounty','setMarineRank','setCareerTitle','clearCareerTitle','endCareerWithEnding',
];

interface Props { value: Effect; onChange: (value: Effect) => void; onRemove: () => void; registries: GameRegistries; eventIds: string[]; scheduledEventIds: string[]; immediateEventIds: string[]; }
export default function EffectEditor({ value, onChange, onRemove, registries, eventIds, scheduledEventIds, immediateEventIds }: Props) {
  const supportsLeadershipOverride = ['acquireShip','loseShip','addCargoItem','removeCargoItem','resolveShipReplacement','setNpcStatus','setNpcPassenger'].includes(value.type);
  const params = (() => {
    switch (value.type) {
      case 'setFlag': case 'clearFlag': return <IdSelect value={value.flagId} options={registries.flags} onChange={(flagId) => onChange({ ...value, flagId })} />;
      case 'addItem': case 'removeItem': case 'addCargoItem': case 'removeCargoItem': return <div className="inline-fields"><IdSelect value={value.itemId} options={registries.items} onChange={(itemId) => onChange({ ...value, itemId })} /><NumberInput value={value.quantity} min={1} onChange={(quantity) => onChange({ ...value, quantity })} /></div>;
      case 'addTrait': case 'removeTrait': return <IdSelect value={value.traitId} options={registries.traits} onChange={(traitId) => onChange({ ...value, traitId })} />;
      case 'modifyStat': return <div className="inline-fields"><select value={value.statId} onChange={(e) => onChange({ ...value, statId: e.target.value as typeof value.statId })}>{PLAYER_STAT_IDS.map((id) => <option key={id}>{id}</option>)}</select><NumberInput value={value.amount} onChange={(amount) => onChange({ ...value, amount })} /></div>;
      case 'modifyHealth': case 'modifyShipHealth': case 'modifyBerries': return <NumberInput value={value.amount} onChange={(amount) => onChange({ ...value, amount })} />;
      case 'acquireShip': return <div className="inline-fields"><IdSelect value={value.shipId} options={registries.ships} onChange={(shipId) => onChange({ ...value, shipId })} /><input value={value.name} placeholder="ship name" onChange={(e) => onChange({ ...value, name: e.target.value })} /><NumberInput value={value.health ?? 0} min={0} onChange={(health) => onChange({ ...value, health: health || undefined })} /></div>;
      case 'resolveShipReplacement': return <div className="inline-fields"><select value={value.disposition} onChange={(e) => onChange({ ...value, disposition: e.target.value as typeof value.disposition })}><option value="destroy">destroy</option><option value="sell">sell</option><option value="abandon">abandon</option></select>{value.disposition === 'sell' && <NumberInput value={value.berries ?? 0} min={0} onChange={(berries) => onChange({ ...value, berries })} />}</div>;
      case 'moveToLocation': case 'loseShip': return <div className="inline-fields"><IdSelect value={value.locationId} options={registries.locations} onChange={(locationId) => onChange({ ...value, locationId })} /><select value={value.travelState} onChange={(e) => onChange({ ...value, travelState: e.target.value as typeof value.travelState })}><option value="at_sea">at_sea</option><option value="on_land">on_land</option></select></div>;
      case 'setBirthLocation': return <IdSelect value={value.locationId} options={registries.locations} onChange={(locationId) => onChange({ ...value, locationId })} />;
      case 'setNpcStatus': return <div className="inline-fields"><IdSelect value={value.npcId} options={registries.npcs} onChange={(npcId) => onChange({ ...value, npcId })} /><select value={value.status} onChange={(e) => onChange({ ...value, status: e.target.value as typeof value.status })}>{NPC_STATUSES.map((x) => <option key={x}>{x}</option>)}</select></div>;
      case 'setNpcPassenger': return <div className="inline-fields"><IdSelect value={value.npcId} options={registries.npcs} onChange={(npcId) => onChange({ ...value, npcId })} /><select value={String(value.passenger)} onChange={(e) => onChange({ ...value, passenger: e.target.value === 'true' })}><option value="true">passenger</option><option value="false">not passenger</option></select></div>;
      case 'setLeadership': return <select value={String(value.isLeader)} onChange={(e) => onChange({ ...value, isLeader: e.target.value === 'true' })}><option value="true">leader</option><option value="false">not leader</option></select>;
      case 'modifyNpcRelationship': return <div className="inline-fields"><IdSelect value={value.npcId} options={registries.npcs} onChange={(npcId) => onChange({ ...value, npcId })} /><NumberInput value={value.amount} onChange={(amount) => onChange({ ...value, amount })} /></div>;
      case 'modifyNpcStat': return <div className="inline-fields"><IdSelect value={value.npcId} options={registries.npcs} onChange={(npcId) => onChange({ ...value, npcId })} /><select value={value.statId} onChange={(e) => onChange({ ...value, statId: e.target.value as typeof value.statId })}>{NPC_STAT_IDS.map((id) => <option key={id}>{id}</option>)}</select><NumberInput value={value.amount} onChange={(amount) => onChange({ ...value, amount })} /></div>;
      case 'scheduleEvent': return <div className="inline-fields"><IdSelect value={value.eventId} options={scheduledEventIds.map((id) => ({ id }))} onChange={(eventId) => onChange({ ...value, eventId })} /><NumberInput value={value.delayMonths} min={0} onChange={(delayMonths) => onChange({ ...value, delayMonths })} /></div>;
      case 'queueImmediateEvent': return <IdSelect value={value.eventId} options={immediateEventIds.map((id) => ({ id }))} onChange={(eventId) => onChange({ ...value, eventId })} />;
      case 'setCareerPhase': return <select value={value.phase} onChange={(e) => onChange({ ...value, phase: e.target.value as typeof value.phase })}><option value="origins">origins</option><option value="childhood">childhood</option><option value="active">active</option></select>;
      case 'setRace': return <IdSelect value={value.raceId} options={registries.races} onChange={(raceId) => onChange({ ...value, raceId })} />;
      case 'setOriginSea': return <IdSelect value={value.seaId} options={registries.seas} onChange={(seaId) => onChange({ ...value, seaId })} />;
      case 'setAffiliation': return <IdSelect value={value.affiliationId} options={registries.affiliations} onChange={(affiliationId) => onChange({ ...value, affiliationId })} />;
      case 'setFamilyStructure': return <IdSelect value={value.familyStructureId} options={registries.familyStructures} onChange={(familyStructureId) => onChange({ ...value, familyStructureId })} />;
      case 'setSocialClass': return <IdSelect value={value.socialClassId} options={registries.socialClasses} onChange={(socialClassId) => onChange({ ...value, socialClassId })} />;
      case 'consumeDevilFruit': return <IdSelect value={value.fruitId} options={registries.devilFruits} onChange={(fruitId) => onChange({ ...value, fruitId })} />;
      case 'increaseDevilFruitAwakening': return <NumberInput value={value.amount} min={1} onChange={(amount) => onChange({ ...value, amount })} />;
      case 'awakenHaki': return <select value={value.hakiType} onChange={(e) => onChange({ ...value, hakiType: e.target.value as typeof value.hakiType })}>{HAKI_TYPES.map((x) => <option key={x}>{x}</option>)}</select>;
      case 'raiseConquerorHakiTo': return <NumberInput value={value.level} min={1} onChange={(level) => onChange({ ...value, level })} />;
      case 'setNpcDevilFruit': return <div className="inline-fields"><IdSelect value={value.npcId} options={registries.npcs} onChange={(npcId) => onChange({ ...value, npcId })} /><IdSelect value={value.fruitId} options={registries.devilFruits} onChange={(fruitId) => onChange({ ...value, fruitId })} /></div>;
      case 'increaseNpcDevilFruitAwakening': return <div className="inline-fields"><IdSelect value={value.npcId} options={registries.npcs} onChange={(npcId) => onChange({ ...value, npcId })} /><NumberInput value={value.amount} min={1} onChange={(amount) => onChange({ ...value, amount })} /></div>;
      case 'raiseNpcHakiTo': return <div className="inline-fields"><IdSelect value={value.npcId} options={registries.npcs} onChange={(npcId) => onChange({ ...value, npcId })} /><select value={value.hakiType} onChange={(e) => onChange({ ...value, hakiType: e.target.value as typeof value.hakiType })}>{HAKI_TYPES.map((x) => <option key={x}>{x}</option>)}</select><NumberInput value={value.level} min={1} onChange={(level) => onChange({ ...value, level })} /></div>;
      case 'endCareer': return <select value={value.reason} onChange={(e) => onChange({ ...value, reason: e.target.value as typeof value.reason })}><option value="death">death</option><option value="legacy">legacy</option></select>;
      case 'setCareerAffiliation': return <IdSelect value={value.affiliationId} options={registries.careerAffiliations} onChange={(affiliationId) => onChange({ ...value, affiliationId: affiliationId as typeof value.affiliationId })} />;
      case 'modifyReputation': case 'modifyBounty': return <NumberInput value={value.amount} onChange={(amount) => onChange({ ...value, amount })} />;
      case 'setBounty': return <NumberInput value={value.value} min={0} onChange={(next) => onChange({ ...value, value: next })} />;
      case 'setMarineRank': return <IdSelect value={value.rankId ?? ''} options={registries.marineRanks} onChange={(rankId) => onChange({ ...value, rankId: rankId || null })} />;
      case 'setCareerTitle': return <IdSelect value={value.titleId} options={registries.careerTitles} onChange={(titleId) => onChange({ ...value, titleId })} />;
      case 'clearCareerTitle': return <span className="muted">No parameters</span>;
      case 'endCareerWithEnding': return <IdSelect value={value.endingId} options={registries.endings} onChange={(endingId) => onChange({ ...value, endingId })} />;
    }
  })();
  return <div className="effect-row"><select value={value.type} onChange={(e) => onChange(createEffect(e.target.value as Effect['type']))}>{EFFECT_TYPES.map((type) => <option key={type}>{type}</option>)}</select><div className="effect-params">{params}{supportsLeadershipOverride && <label className="checkbox-inline"><input type="checkbox" checked={'allowWithoutLeadership' in value && value.allowWithoutLeadership === true} onChange={(e) => onChange({ ...value, allowWithoutLeadership: e.target.checked || undefined } as Effect)} /> narrative leadership override</label>}</div><button className="icon danger" onClick={onRemove}>×</button></div>;
}
