export const NPC_NAME_POOLS: Readonly<Record<string, readonly string[]>> = {
  blue_common: [
    "Abel", "Ada", "Adel", "Aden", "Aiko", "Alba", "Alec", "Alix", "Alma", "Anis",
    "Anja", "Arlo", "Aron", "Asha", "Aster", "Aubin", "Ayla", "Basil", "Bela", "Beni",
    "Bora", "Bran", "Brina", "Cai", "Caio", "Cal", "Caro", "Cass", "Celia", "Ciro",
    "Cléo", "Cora", "Dain", "Dalia", "Dario", "Daya", "Deni", "Dora", "Eden", "Eli",
    "Elio", "Elsa", "Emil", "Enya", "Eren", "Erin", "Ewan", "Ezra", "Fara", "Félix",
    "Fia", "Finn", "Flora", "Gabi", "Gaël", "Gala", "Gino", "Gwen", "Hana", "Haru",
    "Iago", "Ida", "Ilan", "Ilia", "Inès", "Iris", "Isao", "Ivo", "Jade", "Jaro",
    "Jaya", "Jin", "Joan", "Jona", "Jori", "Juno", "Kael", "Kali", "Kara", "Kaya",
    "Kei", "Kian", "Kira", "Koa", "Lana", "Lars", "Lena", "Léo", "Lian", "Lila",
    "Lino", "Lio", "Lise", "Liv", "Lora", "Luan", "Luca", "Lumi", "Malo", "Mara",
    "Marek", "Mavi", "Mika", "Milo", "Mina", "Mirae", "Nami", "Nao", "Nara", "Nell",
    "Nia", "Nico", "Nila", "Nino", "Noa", "Noé", "Nora", "Nova", "Olan", "Olia",
    "Oren", "Orin", "Pia", "Ravi", "Rémi", "Rian", "Rina", "Rio", "Riva", "Romy",
    "Sacha", "Saki", "Sami", "Sena", "Silo", "Sira", "Sol", "Sora", "Tali", "Tao",
    "Tara", "Tess", "Theo", "Tia", "Tilo", "Toma", "Tori", "Uma", "Uri", "Vala",
    "Vasco", "Vega", "Vera", "Viko", "Wren", "Yara", "Yori", "Yuna", "Zia", "Zora",
    "Amaro", "Ansel", "Arden", "Ari", "Aro", "Beniam", "Blaise", "Cami", "Cato", "Davi",
    "Dima", "Eiko", "Elya", "Enzo", "Faye", "Fero", "Gaya", "Hedi", "Ilya", "Jali",
    "Joss", "Kavi", "Keno", "Lali", "Lior", "Maël", "Mako", "Meli", "Miro", "Nael",
    "Niko", "Ona", "Orel", "Paco", "Rami", "Reno", "Riko", "Runa", "Senaï", "Tavi",
    "Teo", "Timo", "Una", "Vani", "Yani", "Yuki", "Zeno", "Amani", "Bayo", "Cassi",
    "Dune", "Faro", "Gio", "Hina", "Iria", "Javi", "Kena", "Lumié", "Mavié", "Nori",
    "Omi", "Pela", "Runaï", "Soli", "Tavié", "Umi", "Veya", "Yorié", "Zali", "Ariane",
    "Beren", "Ciela", "Doran", "Eleni", "Fenna", "Galen", "Halia", "Isen", "Joren", "Kelia",
    "Lorin", "Maia", "Neris", "Orelia", "Perin", "Ravel", "Salen", "Talia", "Ulan", "Varen",
    "Willa", "Yelen", "Zaren",
  ],
  childhood_male: [
    "Abel",
    "Adrien",
    "Aiden",
    "Alban",
    "Alec",
    "Alexis",
    "Amaro",
    "Ansel",
    "Anton",
    "Arden",
    "Arlo",
    "Armand",
    "Aubin",
    "Axel",
    "Basile",
    "Bastien",
    "Benoît",
    "Bran",
    "Cal",
    "Caio",
    "Cato",
    "Cédric",
    "Ciro",
    "Dain",
    "Damien",
    "Dario",
    "Davi",
    "Dorian",
    "Eden",
    "Eli",
    "Elio",
    "Emil",
    "Enzo",
    "Eren",
    "Ewan",
    "Ezra",
    "Faro",
    "Félix",
    "Finn",
    "Gabin",
    "Gaël",
    "Galen",
    "Gino",
    "Haru",
    "Hedi",
    "Hugo",
    "Iago",
    "Ilan",
    "Ivo",
    "Jaro",
    "Javi",
    "Jin",
    "Jona",
    "Joren",
    "Kael",
    "Kavi",
    "Kei",
    "Keno",
    "Kian",
    "Koa",
    "Lars",
    "Léo",
    "Lian",
    "Lino",
    "Lio",
    "Lorin",
    "Luan",
    "Luca",
    "Maël",
    "Mako",
    "Malo",
    "Marek",
    "Mika",
    "Milo",
    "Miro",
    "Nael",
    "Nico",
    "Niko",
    "Nino",
    "Noé",
    "Olan",
    "Oren",
    "Orin",
    "Paco",
    "Perin",
    "Rami",
    "Ravi",
    "Reno",
    "Rian",
    "Rio",
    "Sacha",
    "Sami",
    "Silo",
    "Sol",
    "Tao",
    "Tavi",
    "Théo",
    "Tilo",
    "Timo",
    "Toma",
    "Uri",
    "Varen",
    "Vasco",
    "Viko",
    "Yani",
    "Yori",
    "Zaren",
    "Zeno"
  ],
  childhood_female: [
    "Ada",
    "Aiko",
    "Alba",
    "Alix",
    "Alma",
    "Anja",
    "Ariane",
    "Asha",
    "Ayla",
    "Bela",
    "Brina",
    "Caro",
    "Cassia",
    "Célia",
    "Ciela",
    "Cléo",
    "Cora",
    "Dalia",
    "Daya",
    "Dora",
    "Eleni",
    "Elsa",
    "Enya",
    "Erin",
    "Fara",
    "Faye",
    "Fenna",
    "Fia",
    "Flora",
    "Gala",
    "Gaya",
    "Gwen",
    "Halia",
    "Hana",
    "Hina",
    "Ida",
    "Ilia",
    "Inès",
    "Iria",
    "Iris",
    "Jade",
    "Jaya",
    "Juno",
    "Kali",
    "Kara",
    "Kaya",
    "Kelia",
    "Kena",
    "Kira",
    "Lana",
    "Léna",
    "Lila",
    "Lise",
    "Liv",
    "Lora",
    "Lumi",
    "Maia",
    "Mara",
    "Mavi",
    "Meli",
    "Mina",
    "Nara",
    "Nell",
    "Nia",
    "Nila",
    "Nora",
    "Nova",
    "Olia",
    "Ona",
    "Orelia",
    "Pia",
    "Rina",
    "Riva",
    "Romy",
    "Runa",
    "Saki",
    "Sena",
    "Sira",
    "Sora",
    "Tali",
    "Talia",
    "Tara",
    "Tess",
    "Tia",
    "Tori",
    "Uma",
    "Una",
    "Vala",
    "Vani",
    "Vega",
    "Vera",
    "Veya",
    "Willa",
    "Yara",
    "Yelen",
    "Yuna",
    "Zali",
    "Zia",
    "Zora"
  ],
};
