export type UITunerSectionId =
  | 'foundation'
  | 'hud'
  | 'event'
  | 'stats'
  | 'crew'
  | 'outcome'
  | 'tooltips'
  | 'glass'
  | 'palette';

export type UITunerRangeDefinition = {
  kind: 'range';
  id: string;
  label: string;
  description?: string;
  section: UITunerSectionId;
  variable: string;
  defaultValue: number;
  min: number;
  max: number;
  step: number;
  unit: string;
};

export type UITunerColorDefinition = {
  kind: 'color';
  id: string;
  label: string;
  description?: string;
  section: UITunerSectionId;
  variable: string;
  defaultValue: string;
};

export type UITunerDefinition =
  | UITunerRangeDefinition
  | UITunerColorDefinition;

export type UITunerValue = number | string;
export type UITunerValues = Record<string, UITunerValue>;

export const UI_TUNER_SECTIONS: Array<{
  id: UITunerSectionId;
  label: string;
}> = [
  { id: 'foundation', label: 'Fondations' },
  { id: 'hud', label: 'HUD supérieur' },
  { id: 'event', label: 'Events / Choices' },
  { id: 'stats', label: 'Stats joueur' },
  { id: 'crew', label: 'Crew' },
  { id: 'outcome', label: 'Outcomes' },
  { id: 'tooltips', label: 'Tooltips' },
  { id: 'glass', label: 'Boutons glass' },
  { id: 'palette', label: 'Palette stats' },
];

const range = (
  id: string,
  label: string,
  section: UITunerSectionId,
  variable: string,
  defaultValue: number,
  min: number,
  max: number,
  step: number,
  unit: string,
  description?: string,
): UITunerRangeDefinition => ({
  kind: 'range',
  id,
  label,
  section,
  variable,
  defaultValue,
  min,
  max,
  step,
  unit,
  description,
});

const color = (
  id: string,
  label: string,
  section: UITunerSectionId,
  variable: string,
  defaultValue: string,
  description?: string,
): UITunerColorDefinition => ({
  kind: 'color',
  id,
  label,
  section,
  variable,
  defaultValue,
  description,
});

export const UI_TUNER_DEFINITIONS: UITunerDefinition[] = [
  range(
    'layoutGutter',
    'Gouttière globale',
    'foundation',
    '--ui-layout-gutter',
    24,
    8,
    48,
    1,
    'px',
  ),
  range(
    'panelRadius',
    'Radius panels',
    'foundation',
    '--ui-panel-radius',
    16,
    0,
    32,
    1,
    'px',
  ),
  range(
    'controlRadius',
    'Radius contrôles',
    'foundation',
    '--ui-control-radius',
    12,
    0,
    24,
    1,
    'px',
  ),
  range(
    'surfaceRaisedAlpha',
    'Opacité panels',
    'foundation',
    '--ui-surface-raised-alpha',
    82,
    35,
    100,
    1,
    '%',
  ),
  range(
    'surfaceStrongAlpha',
    'Opacité panels forts',
    'foundation',
    '--ui-surface-strong-alpha',
    92,
    45,
    100,
    1,
    '%',
  ),
  range(
    'borderDefaultAlpha',
    'Alpha bordures',
    'foundation',
    '--ui-border-default-alpha',
    20,
    0,
    70,
    1,
    '%',
  ),
  range(
    'borderStrongAlpha',
    'Alpha bordures fortes',
    'foundation',
    '--ui-border-strong-alpha',
    32,
    0,
    80,
    1,
    '%',
  ),
  range(
    'shadowPanelAlpha',
    'Ombre panels',
    'foundation',
    '--ui-shadow-panel-alpha',
    30,
    0,
    70,
    1,
    '%',
  ),
  range(
    'motionNormal',
    'Motion normale',
    'foundation',
    '--ui-motion-normal',
    180,
    1,
    600,
    5,
    'ms',
  ),

  range(
    'hudMinHeight',
    'Hauteur mini',
    'hud',
    '--ui-hud-min-height',
    116,
    82,
    190,
    1,
    'px',
  ),
  range(
    'hudSectionPx',
    'Padding horizontal',
    'hud',
    '--ui-hud-section-px',
    17,
    4,
    36,
    1,
    'px',
  ),
  range(
    'hudSectionPy',
    'Padding vertical',
    'hud',
    '--ui-hud-section-py',
    16,
    4,
    30,
    1,
    'px',
  ),
  range(
    'hudInventoryFr',
    'Largeur Inventaire',
    'hud',
    '--ui-hud-inventory-fr',
    0.55,
    0.3,
    1.4,
    0.05,
    'fr',
  ),
  range(
    'hudWorldFr',
    'Largeur Monde',
    'hud',
    '--ui-hud-world-fr',
    0.95,
    0.4,
    1.8,
    0.05,
    'fr',
  ),
  range(
    'hudPlayerFr',
    'Largeur Joueur',
    'hud',
    '--ui-hud-player-fr',
    0.72,
    0.4,
    1.5,
    0.05,
    'fr',
  ),
  range(
    'hudShipFr',
    'Largeur Navire',
    'hud',
    '--ui-hud-ship-fr',
    1.2,
    0.6,
    2.2,
    0.05,
    'fr',
  ),
  range(
    'hudSlotSize',
    'Taille slots',
    'hud',
    '--ui-hud-slot-size',
    34.4,
    22,
    56,
    0.5,
    'px',
  ),
  range(
    'hudSlotGap',
    'Gap slots',
    'hud',
    '--ui-hud-slot-gap',
    5.4,
    0,
    16,
    0.5,
    'px',
  ),
  range(
    'hudSlotRadius',
    'Radius slots',
    'hud',
    '--ui-hud-slot-radius',
    6.7,
    0,
    18,
    0.5,
    'px',
  ),
  range(
    'hudCargoOffset',
    'Décalage cale',
    'hud',
    '--ui-hud-cargo-offset',
    51,
    0,
    90,
    1,
    'px',
  ),
  range(
    'hudShipIconSize',
    'Icône navire',
    'hud',
    '--ui-hud-ship-icon-size',
    40,
    24,
    64,
    1,
    'px',
  ),
  range(
    'hudPrimarySize',
    'Texte principal',
    'hud',
    '--ui-hud-primary-size',
    17,
    11,
    26,
    0.5,
    'px',
  ),
  range(
    'hudSecondarySize',
    'Texte secondaire',
    'hud',
    '--ui-hud-secondary-size',
    11.7,
    8,
    18,
    0.1,
    'px',
  ),
  range(
    'hudNameSize',
    'Nom personnage',
    'hud',
    '--ui-hud-name-size',
    20,
    12,
    34,
    0.5,
    'px',
  ),

  range(
    'eventHeaderPx',
    'Header X',
    'event',
    '--ui-event-header-px',
    28,
    8,
    48,
    1,
    'px',
  ),
  range(
    'eventHeaderPt',
    'Header haut',
    'event',
    '--ui-event-header-pt',
    16,
    4,
    36,
    1,
    'px',
  ),
  range(
    'eventHeaderPb',
    'Header bas',
    'event',
    '--ui-event-header-pb',
    12,
    4,
    36,
    1,
    'px',
  ),
  range(
    'eventBodyPx',
    'Texte X',
    'event',
    '--ui-event-body-px',
    28,
    8,
    48,
    1,
    'px',
  ),
  range(
    'eventBodyPt',
    'Texte haut',
    'event',
    '--ui-event-body-pt',
    16,
    4,
    36,
    1,
    'px',
  ),
  range(
    'eventBodyPb',
    'Texte bas',
    'event',
    '--ui-event-body-pb',
    20,
    4,
    40,
    1,
    'px',
  ),
  range(
    'eventTitleSize',
    'Titre Event',
    'event',
    '--ui-event-title-size',
    24,
    16,
    40,
    0.5,
    'px',
  ),
  range(
    'eventBodySize',
    'Corps Event',
    'event',
    '--ui-event-body-size',
    15,
    11,
    22,
    0.5,
    'px',
  ),
  range(
    'eventBodyLeading',
    'Interligne Event',
    'event',
    '--ui-event-body-leading',
    24,
    16,
    36,
    1,
    'px',
  ),
  range(
    'choiceMinHeight',
    'Hauteur Choice',
    'event',
    '--ui-choice-min-height',
    56,
    36,
    92,
    1,
    'px',
  ),
  range(
    'choiceGap',
    'Gap Choices',
    'event',
    '--ui-choice-gap',
    10,
    2,
    28,
    1,
    'px',
  ),
  range(
    'choicePx',
    'Choice X',
    'event',
    '--ui-choice-px',
    20,
    6,
    40,
    1,
    'px',
  ),
  range(
    'choicePy',
    'Choice Y',
    'event',
    '--ui-choice-py',
    12,
    4,
    28,
    1,
    'px',
  ),
  range(
    'choiceTextSize',
    'Texte Choice',
    'event',
    '--ui-choice-text-size',
    14,
    10,
    20,
    0.5,
    'px',
  ),

  range(
    'statsCompactWidth',
    'Rail fermé',
    'stats',
    '--ui-stats-compact-width',
    84,
    58,
    130,
    1,
    'px',
  ),
  range(
    'statsExpandedWidth',
    'Rail ouvert',
    'stats',
    '--ui-stats-expanded-width',
    224,
    150,
    340,
    1,
    'px',
  ),
  range(
    'statRowHeight',
    'Hauteur ligne',
    'stats',
    '--ui-stat-row-height',
    49,
    34,
    72,
    1,
    'px',
  ),
  range(
    'statIconSize',
    'Icône stat',
    'stats',
    '--ui-stat-icon-size',
    24.8,
    12,
    40,
    0.5,
    'px',
  ),
  range(
    'statWatermarkSize',
    'Watermark',
    'stats',
    '--ui-stat-watermark-size',
    99,
    45,
    150,
    1,
    'px',
  ),
  range(
    'statWatermarkOpacity',
    'Alpha watermark',
    'stats',
    '--ui-stat-watermark-opacity',
    0.2,
    0,
    0.6,
    0.01,
    '',
  ),
  range(
    'statLabelSize',
    'Label stat',
    'stats',
    '--ui-stat-label-size',
    12.2,
    8,
    18,
    0.1,
    'px',
  ),
  range(
    'statValueSize',
    'Valeur stat',
    'stats',
    '--ui-stat-value-size',
    13.1,
    8,
    20,
    0.1,
    'px',
  ),
  range(
    'statGaugeHeight',
    'Jauge',
    'stats',
    '--ui-stat-gauge-height',
    6.7,
    2,
    14,
    0.2,
    'px',
  ),
  range(
    'traitsHeight',
    'Zone Traits',
    'stats',
    '--ui-traits-height',
    81,
    48,
    140,
    1,
    'px',
  ),

  range(
    'crewWidth',
    'Crew fermé',
    'crew',
    '--ui-crew-width',
    160,
    110,
    240,
    1,
    'px',
  ),
  range(
    'crewExpandedWidth',
    'Crew ouvert',
    'crew',
    '--ui-crew-expanded-width',
    288,
    190,
    420,
    1,
    'px',
  ),
  range(
    'crewGap',
    'Gap membres',
    'crew',
    '--ui-crew-gap',
    6.7,
    0,
    20,
    0.5,
    'px',
  ),
  range(
    'crewRowHeight',
    'Hauteur membre',
    'crew',
    '--ui-crew-row-height',
    42.4,
    30,
    72,
    0.5,
    'px',
  ),
  range(
    'crewNameSize',
    'Nom membre',
    'crew',
    '--ui-crew-name-size',
    12.8,
    9,
    20,
    0.1,
    'px',
  ),

  range(
    'outcomeEffectHeight',
    'Hauteur effet',
    'outcome',
    '--ui-outcome-effect-height',
    32,
    22,
    54,
    1,
    'px',
  ),
  range(
    'outcomeEffectGap',
    'Gap effets',
    'outcome',
    '--ui-outcome-effect-gap',
    8,
    2,
    22,
    1,
    'px',
  ),
  range(
    'outcomeEffectIcon',
    'Icône effet',
    'outcome',
    '--ui-outcome-effect-icon-size',
    17.3,
    10,
    30,
    0.2,
    'px',
  ),
  range(
    'impactDuration',
    'Durée impact',
    'outcome',
    '--ui-impact-duration',
    760,
    120,
    1800,
    10,
    'ms',
  ),
  range(
    'impactNumberSize',
    'Nombre impact',
    'outcome',
    '--ui-impact-number-size',
    32.6,
    12,
    80,
    0.5,
    'px',
  ),
  range(
    'impactWatermarkSize',
    'Nombre watermark',
    'outcome',
    '--ui-impact-watermark-size',
    92.8,
    30,
    180,
    1,
    'px',
  ),
  range(
    'impactWatermarkAlpha',
    'Alpha impact watermark',
    'outcome',
    '--ui-impact-watermark-alpha',
    0.2,
    0,
    0.6,
    0.01,
    '',
  ),

  range(
    'tooltipMaxWidth',
    'Largeur max',
    'tooltips',
    '--ui-tooltip-max-width',
    320,
    180,
    520,
    5,
    'px',
  ),
  range(
    'tooltipRadius',
    'Radius',
    'tooltips',
    '--ui-tooltip-radius',
    11.5,
    0,
    26,
    0.5,
    'px',
  ),
  range(
    'tooltipPx',
    'Padding X',
    'tooltips',
    '--ui-tooltip-px',
    12.5,
    4,
    30,
    0.5,
    'px',
  ),
  range(
    'tooltipPy',
    'Padding Y',
    'tooltips',
    '--ui-tooltip-py',
    11,
    4,
    30,
    0.5,
    'px',
  ),
  range(
    'tooltipTitleSize',
    'Titre',
    'tooltips',
    '--ui-tooltip-title-size',
    12.5,
    8,
    20,
    0.1,
    'px',
  ),
  range(
    'tooltipDetailSize',
    'Description',
    'tooltips',
    '--ui-tooltip-detail-size',
    11.2,
    8,
    18,
    0.1,
    'px',
  ),

  range(
    'glassBlur',
    'Blur',
    'glass',
    '--ui-glass-blur',
    5,
    0,
    20,
    0.5,
    'px',
  ),
  range(
    'glassSaturation',
    'Saturation',
    'glass',
    '--ui-glass-saturation',
    1.08,
    0.5,
    2,
    0.01,
    '',
  ),
  range(
    'glassBorderAlpha',
    'Bordure',
    'glass',
    '--ui-glass-border-alpha',
    42,
    0,
    100,
    1,
    '%',
  ),
  range(
    'glassHoverBorderAlpha',
    'Bordure hover',
    'glass',
    '--ui-glass-hover-border-alpha',
    58,
    0,
    100,
    1,
    '%',
  ),
  range(
    'glassShadowY',
    'Ombre Y',
    'glass',
    '--ui-glass-shadow-y',
    6,
    0,
    24,
    1,
    'px',
  ),
  range(
    'glassShadowBlur',
    'Ombre blur',
    'glass',
    '--ui-glass-shadow-blur',
    18,
    0,
    60,
    1,
    'px',
  ),
  range(
    'glassStretchX',
    'Stretch hover X',
    'glass',
    '--ui-glass-hover-stretch-x',
    1.012,
    0.98,
    1.08,
    0.001,
    '',
  ),
  range(
    'glassStretchY',
    'Stretch hover Y',
    'glass',
    '--ui-glass-hover-stretch-y',
    0.998,
    0.94,
    1.04,
    0.001,
    '',
  ),

  color(
    'healthColor',
    'Santé',
    'palette',
    '--opfg-stat-health',
    '#c94f4a',
  ),
  color(
    'moraleColor',
    'Moral',
    'palette',
    '--opfg-stat-morale',
    '#4fa58b',
  ),
  color(
    'strengthColor',
    'Force',
    'palette',
    '--opfg-stat-strength',
    '#d8783f',
  ),
  color(
    'agilityColor',
    'Agilité',
    'palette',
    '--opfg-stat-agility',
    '#8aaa4d',
  ),
  color(
    'observationColor',
    'Observation',
    'palette',
    '--opfg-stat-observation',
    '#54a9b7',
  ),
  color(
    'intelligenceColor',
    'Intelligence',
    'palette',
    '--opfg-stat-intelligence',
    '#806eb0',
  ),
  color(
    'navigationColor',
    'Navigation',
    'palette',
    '--opfg-stat-navigation',
    '#397fa8',
  ),
  color(
    'charismaColor',
    'Charisme',
    'palette',
    '--opfg-stat-charisma',
    '#bd6687',
  ),
  color(
    'luckColor',
    'Chance',
    'palette',
    '--opfg-stat-luck',
    '#d1a33c',
  ),
];

export const UI_TUNER_DEFAULT_VALUES: UITunerValues =
  Object.fromEntries(
    UI_TUNER_DEFINITIONS.map((definition) => [
      definition.id,
      definition.defaultValue,
    ]),
  );

export const UI_TUNER_QUICK_PRESETS: Array<{
  id: string;
  label: string;
  values: Partial<UITunerValues>;
}> = [
  {
    id: 'compact',
    label: 'Compact',
    values: {
      hudMinHeight: 96,
      hudSectionPx: 12,
      hudSectionPy: 10,
      hudSlotSize: 29,
      hudSlotGap: 4,
      statsCompactWidth: 74,
      statsExpandedWidth: 202,
      statRowHeight: 43,
      statIconSize: 21,
      statWatermarkSize: 86,
      traitsHeight: 68,
      crewWidth: 148,
      crewExpandedWidth: 260,
      crewRowHeight: 38,
      choiceMinHeight: 48,
      choiceGap: 7,
      choicePy: 9,
      eventBodyPb: 14,
    },
  },
  {
    id: 'balanced',
    label: 'Balanced',
    values: UI_TUNER_DEFAULT_VALUES,
  },
  {
    id: 'spacious',
    label: 'Spacious',
    values: {
      hudMinHeight: 136,
      hudSectionPx: 22,
      hudSectionPy: 20,
      hudSlotSize: 40,
      hudSlotGap: 7,
      statsCompactWidth: 96,
      statsExpandedWidth: 250,
      statRowHeight: 55,
      statIconSize: 28,
      statWatermarkSize: 112,
      traitsHeight: 92,
      crewWidth: 176,
      crewExpandedWidth: 320,
      crewRowHeight: 48,
      choiceMinHeight: 64,
      choiceGap: 13,
      choicePy: 15,
    },
  },
  {
    id: 'cinematic',
    label: 'Cinematic',
    values: {
      surfaceRaisedAlpha: 72,
      surfaceStrongAlpha: 84,
      borderDefaultAlpha: 16,
      borderStrongAlpha: 26,
      shadowPanelAlpha: 42,
      panelRadius: 18,
      glassBlur: 8,
      glassSaturation: 1.18,
      glassBorderAlpha: 34,
      hudNameSize: 23,
      statWatermarkOpacity: 0.27,
      tooltipRadius: 14,
    },
  },
];
